### ISSUE TITLE
conflicting information for number of training examples to be submitted

### ISSUE THREAD

**Issue by meghbhalerao** [CoactiveAI/dataperf-vision-selection#14]
https://www.dataperf.org/training-set-selection-vision/vision-rules this says the submission should be limited to 1000 points while the google doc says https://docs.google.com/document/d/15ACh9pNn16GjgJKVRuBHhtiIMhhRIMkd_yPjFyb9JcE/edit 500 datapoints. 

which one is correct? 

please do let me know and I look forward to your response!

**Comment by willgaviria** [comment]
Hi Megh,

Great question. The mentioned google doc is meant to be private (as such we have removed the link from this repo), while all the publicly available information [here](https://dynabench.org/tasks/vision-selection) (see "Documentation" link) is meant to be the source of truth for the challenges going forward.

With that in mind, 1000 datapoints is the current limit at this time.

Hope this answers your question!
